version: '3.8'

services:
#   mysql:
#     image: 'mysql:8.0'
#     environment:
#       MYSQL_ROOT_PASSWORD: 'password'
#       MYSQL_DATABASE: 'book_management_system'
#     ports:
#       - '3306:3306'
#     volumes:
#       - 'mysql_data:/var/lib/mysql'
#     networks:
#       - app-network

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge


